FROM node:20-alpine AS builder

WORKDIR /app

# 1. Copy only dependencies files
COPY package*.json yarn.lock* pnpm-lock.yaml* ./

# 2. Install dependencies (postinstall will fail if prisma schema not exists yet)
RUN yarn install --frozen-lockfile || npm install || pnpm install

# 3. Copy prisma + source code
COPY prisma ./prisma
COPY . .

# 4. Build + generate Prisma client
RUN yarn build
RUN npx prisma generate
