version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: hash-backend-dev
    ports:
      - '5000:5000'
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - ./prisma:/app/prisma
